language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
branches:
  only:
    - master
sudo: required
services:
  - docker
env:
  - PYTEST_EXPRESSION="not test_build_image_"
  - PYTEST_EXPRESSION="test_build_image_ants_"
  - PYTEST_EXPRESSION="test_build_image_fsl_"
  - PYTEST_EXPRESSION="test_build_image_spm_"
before_install:
  - travis_retry sudo apt-get update && sudo apt-get install -yq docker-engine
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install pytest-cov
script:
  - travis_wait 50 py.test -v -k=\'$PYTEST_EXPRESSION\' --cov=./ neurodocker
after_success:
  - bash <(curl -s https://codecov.io/bash)
