language: python
python:
  - 2.7
  - 3.5
  - 3.6
branches:
  only:
    - master
sudo: required
services:
  - docker
env:
  - IMAGE_TO_BUILD=none
  - IMAGE_TO_BUILD=ants
  - IMAGE_TO_BUILD=fsl
  - IMAGE_TO_BUILD=spm
before_install:
  - travis_retry sudo apt-get update && sudo apt-get install -yq docker-engine
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install pytest-cov
script:
  - function run_tests {
      if [ "$IMAGE_TO_BUILD" == 'none' ]; then
        pytest -v -k "not test_build_image" --cov=./ neurodocker;
      else
        travis_wait 50 pytest -v -k "test_build_image_$IMAGE_TO_BUILD" --cov=./ neurodocker;
      fi }
  - run_tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
