language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
branches:
  only:
    - master
sudo: required
services:
  - docker
env:
  - BUILD_IMAGES=true
  - BUILD_IMAGES=false
before_install:
  - travis_retry sudo apt-get update && sudo apt-get install -yq docker-engine
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install pytest-cov
script:
  - function run_tests {
    if $BUILD_IMAGES; then
      travis_wait 90 py.test -v -k "test_build_image_" --cov=./ neurodocker;
    else
      py.test -v -k "not test_build_image_" --cov=./ neurodocker;
    fi }
  - run_tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
