coverage:
  branch: master
  range: 0...100
  status:
    patch:
      default:
        target: 0
        threshold: 100
    project:
      default:
        target: 0
        threshold: 100
comment:
  layout: "header, diff"
  behavior: default
