---
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201710-02
    working_directory: /root
    steps:
      - checkout:
          path: ~/neurodocker
      - run:
          command: |
            pip3 install dropbox pytest-cov reprozip
            pip3 install -e ~/neurodocker
      - run:
          command: |
            docker create -v /testscripts --name data-container alpine:3.7 /bin/true
            docker cp ~/neurodocker/neurodocker/interfaces/tests/. data-container:/testscripts
      - run: pytest ~/neurodocker/neurodocker

# TODO: Fan out to parallelize docker builds in tests.

# TODO: add deploy step
#   - require the tests to pass before deploying.
#   - include logic to update version based on git hash.
#   - only deploy on pushes to master / releases.
#   - deploy Docker image to DockerHub
#   - upload wheels to PyPI.
