---
version: 2
jobs:
  build:
    docker:
      - image: kaczmarj/neurodocker:circleci
    working_directory: ~
    steps:
      - checkout:
          path: ~/neurodocker
      - run:
          command: |
            ls ~
            ls ~/neurodocker
            pip3 install dropbox pytest-cov reprozip
            pip3 install -e neurodocker
      - setup_remote_docker
      - run: pytest neurodocker

# TODO: Fan out to parallelize docker builds in tests.

# TODO: add deploy step
#   - require the tests to pass before deploying.
#   - include logic to update version based on git hash.
#   - only deploy on pushes to master / releases.
#   - deploy Docker image to DockerHub
#   - upload wheels to PyPI.
