---
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201711-01
    steps:
      - checkout:
          path: ~/neurodocker
      - run:
          command: |
            pyenv global 3.5.2
            pip install -U pip
            pip install dropbox pytest-cov reprozip
            pip install -e ~/neurodocker
      - run: pytest -s ~/neurodocker/neurodocker/interfaces/tests/test_convert3d.py ~/neurodocker/neurodocker/interfaces/tests/test_dcm2niix.py

# TODO: Fan out to parallelize docker builds in tests.

# TODO: add deploy step
#   - require the tests to pass before deploying.
#   - include logic to update version based on git hash.
#   - only deploy on pushes to master / releases.
#   - deploy Docker image to DockerHub
#   - upload wheels to PyPI.
