---
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201711-01
    steps:
      - checkout:
          path: ~/neurodocker
      - run:
          command: |
            pyenv global 3.5.2
            pip install -U --no-cache-dir pip
            pip install --no-cache-dir dropbox pytest-cov reprozip
            pip install -e ~/neurodocker
      - run:
          no_output_timeout: 60m
          command: |
            pytest -k 'test_docker' ~/neurodocker/neurodocker

# TODO: Fan out to parallelize docker builds in tests.

# TODO: add deploy step
#   - require the tests to pass before deploying.
#   - include logic to update version based on git hash.
#   - only deploy on pushes to master / releases.
#   - deploy Docker image to DockerHub
#   - upload wheels to PyPI.
