---
_machine_kwds: &machine_kwds
  image: circleci/classic:201711-01

_checkout_kwds: &_checkout_kwds
  path: ~/neurodocker

_setup_env: &_setup_kwds
  name: Setup environment
  command: |
    pyenv global 3.5.2
    pip install -U --no-cache-dir pip
    pip install --no-cache-dir dropbox pytest-cov reprozip
    pip install -e ~/neurodocker

_setup: &setup
  - checkout:
      *_checkout_kwds
  - run:
      *_setup_kwds


version: 2
jobs:
  test_docker:
    machine:
      *machine_kwds
    steps:
      - *setup
      - run:
          no_output_timeout: 360m
          command: |
            pytest -k 'test_docker' ~/neurodocker/neurodocker

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test_docker

# TODO(kaczmarj): add test_singularity step
